export enum PositionStatus {
  PENDING_EXECUTION = "PENDING_EXECUTION",
  ACTIVE = "ACTIVE",
  OUT_OF_RANGE = "OUT_OF_RANGE",
  LIQUIDATION_PENDING = "LIQUIDATION_PENDING",
  LIQUIDATED = "LIQUIDATED",
  FAILED = "FAILED",
}

export enum ActivityType {
  INVESTMENT = "INVESTMENT",
  WITHDRAWAL = "WITHDRAWAL",
  LIQUIDATION = "LIQUIDATION",
  AUTO_REBALANCE = "AUTO_REBALANCE",
  ERROR = "ERROR",
}

export enum ActivityStatus {
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED",
}
