/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IXTokens__factory } from "./IXTokens__factory";
export { MoonbeamXTokensSender__factory } from "./MoonbeamXTokensSender__factory";
