/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXcmSender,
  IXcmSenderInterface,
} from "../../../../contracts/V1(Current)/xcm/IXcmSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendXcm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXcmSender__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmSenderInterface {
    return new Interface(_abi) as IXcmSenderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IXcmSender {
    return new Contract(address, _abi, runner) as unknown as IXcmSender;
  }
}
