/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAlgebraPoolImmutables,
  IAlgebraPoolImmutablesInterface,
} from "../../../../../../@cryptoalgebra/integral-core/contracts/interfaces/pool/IAlgebraPoolImmutables";

const _abi = [
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxLiquidityPerTick",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAlgebraPoolImmutables__factory {
  static readonly abi = _abi;
  static createInterface(): IAlgebraPoolImmutablesInterface {
    return new Interface(_abi) as IAlgebraPoolImmutablesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAlgebraPoolImmutables {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAlgebraPoolImmutables;
  }
}
