# Foundry Configuration for LiquiDOT Smart Contracts
# See: https://book.getfoundry.sh/reference/config/overview

[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test/foundry"
cache_path = "cache_foundry"

# Solidity compiler settings
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
fuzz_runs = 256
ffi = false

# Gas reporting
gas_reports = ["AssetHubVault", "XCMProxy"]
gas_reports_ignore = []

# Remappings for imports
remappings = [
    "forge-std/=node_modules/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@cryptoalgebra/=node_modules/@cryptoalgebra/"
]

# RPC endpoints (for testnet testing)
[rpc_endpoints]
assethub = "${ASSETHUB_RPC}"
moonbase = "${MOONBASE_RPC}"

# Etherscan settings (for verification)
[etherscan]
moonbase = { key = "${MOONSCAN_API_KEY}", chain = 1287, url = "https://api-moonbase.moonscan.io/api" }

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# Test runner settings
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000

# Documentation
[doc]
out = "docs/foundry"
title = "LiquiDOT Smart Contracts"
ignore = ["test/**"]

