[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@cryptoalgebra/=node_modules/@cryptoalgebra/"
]
