/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPalletXcm__factory } from "./IPalletXcm__factory";
export { IXCMTransactor__factory } from "./IXCMTransactor__factory";
export { XCMProxy__factory } from "./XCMProxy__factory";
