/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IXCMTransactor__factory } from "./IXCMTransactor__factory";
export { IXTokens__factory } from "./IXTokens__factory";
export { XCMProxy__factory } from "./XCMProxy__factory";
