/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXTokens,
  IXTokensInterface,
} from "../../../../contracts/V1(Current)/XCMProxy.sol/IXTokens";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "dest",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "destWeight",
        type: "uint64",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXTokens__factory {
  static readonly abi = _abi;
  static createInterface(): IXTokensInterface {
    return new Interface(_abi) as IXTokensInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IXTokens {
    return new Contract(address, _abi, runner) as unknown as IXTokens;
  }
}
