/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetHubVault,
  IAssetHubVaultInterface,
} from "../../../../contracts/test/ReentrancyAttacker.sol/IAssetHubVault";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetHubVault__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetHubVaultInterface {
    return new Interface(_abi) as IAssetHubVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetHubVault {
    return new Contract(address, _abi, runner) as unknown as IAssetHubVault;
  }
}
