/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  AssetHubXcmSender,
  AssetHubXcmSenderInterface,
} from "../../../../../contracts/V1(Current)/xcm/AssetHubXcmSender.sol/AssetHubXcmSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "xcmAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_authorizedCaller",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "UnauthorizedCaller",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "XCM_PRECOMPILE",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "authorizedCaller",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendXcm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "xcm",
    outputs: [
      {
        internalType: "contract IXcm",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c0346100c857601f6103ce38819003918201601f19168301916001600160401b038311848410176100cd5780849260409485528339810103126100c857610052602061004b836100e3565b92016100e3565b906001600160a01b038216156100b7576001600160a01b0381166100b25750620a00005b6001600160a01b031660805260a0526040516102d690816100f8823960805181818160aa015261015f015260a0518181816062015261012c0152f35b610076565b63d92e233d60e01b60005260046000fd5b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b03821682036100c85756fe608080604052600436101561001357600080fd5b600090813560e01c908163077120cc14610230575080635497670b146100d957806384f24c4b14610094576397dc97cb1461004d57600080fd5b346100915780600319360112610091576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b80fd5b50346100915780600319360112610091576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b5034610091576040366003190112610091576004356001600160401b03811161022c5761010a90369060040161024d565b6024356001600160401b0381116102285761012990369060040161024d565b927f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03163303610219578492917f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03169190823b15610215576101be936101d0869260405198899788968795637f0a3bf960e01b875260406004880152604487019161027f565b8481036003190160248601529161027f565b03925af1801561020a576101e2575080f35b6001600160401b0381116101f65760405280f35b634e487b7160e01b82526041600452602482fd5b6040513d84823e3d90fd5b8480fd5b635c427cd960e01b8552600485fd5b8380fd5b5080fd5b90503461022c578160031936011261022c5780620a000060209252f35b9181601f8401121561027a578235916001600160401b03831161027a576020838186019501011161027a57565b600080fd5b908060209392818452848401376000828201840152601f01601f191601019056fea264697066735822122046a840f835a59c12d732ebc49557df8b7d4ebe98abae781d51029d1a5b569f7664736f6c634300081c0033";

type AssetHubXcmSenderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssetHubXcmSenderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AssetHubXcmSender__factory extends ContractFactory {
  constructor(...args: AssetHubXcmSenderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    xcmAddress: AddressLike,
    _authorizedCaller: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      xcmAddress,
      _authorizedCaller,
      overrides || {}
    );
  }
  override deploy(
    xcmAddress: AddressLike,
    _authorizedCaller: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      xcmAddress,
      _authorizedCaller,
      overrides || {}
    ) as Promise<
      AssetHubXcmSender & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AssetHubXcmSender__factory {
    return super.connect(runner) as AssetHubXcmSender__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssetHubXcmSenderInterface {
    return new Interface(_abi) as AssetHubXcmSenderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AssetHubXcmSender {
    return new Contract(address, _abi, runner) as unknown as AssetHubXcmSender;
  }
}
