/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type WeightStruct = { refTime: BigNumberish; proofSize: BigNumberish };

export type WeightStructOutput = [refTime: bigint, proofSize: bigint] & {
  refTime: bigint;
  proofSize: bigint;
};

export interface XcmExecuteAdapterInterface extends Interface {
  getFunction(
    nameOrSignature: "XCM_PRECOMPILE" | "authorizedCaller" | "send"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "XcmExecutionForwarded"): EventFragment;

  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
}

export namespace XcmExecutionForwardedEvent {
  export type InputTuple = [message: BytesLike, weight: WeightStruct];
  export type OutputTuple = [message: string, weight: WeightStructOutput];
  export interface OutputObject {
    message: string;
    weight: WeightStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XcmExecuteAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): XcmExecuteAdapter;
  waitForDeployment(): Promise<this>;

  interface: XcmExecuteAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  authorizedCaller: TypedContractMethod<[], [string], "view">;

  send: TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "XcmExecutionForwarded"
  ): TypedContractEvent<
    XcmExecutionForwardedEvent.InputTuple,
    XcmExecutionForwardedEvent.OutputTuple,
    XcmExecutionForwardedEvent.OutputObject
  >;

  filters: {
    "XcmExecutionForwarded(bytes,tuple)": TypedContractEvent<
      XcmExecutionForwardedEvent.InputTuple,
      XcmExecutionForwardedEvent.OutputTuple,
      XcmExecutionForwardedEvent.OutputObject
    >;
    XcmExecutionForwarded: TypedContractEvent<
      XcmExecutionForwardedEvent.InputTuple,
      XcmExecutionForwardedEvent.OutputTuple,
      XcmExecutionForwardedEvent.OutputObject
    >;
  };
}
