/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IAlgebraPoolPermissionedActionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "setCommunityFee"
      | "setCommunityVault"
      | "setFee"
      | "setPlugin"
      | "setPluginConfig"
      | "setTickSpacing"
      | "skim"
      | "sync"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setCommunityFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommunityVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlugin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTickSpacing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "skim", values?: undefined): string;
  encodeFunctionData(functionFragment: "sync", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "setCommunityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCommunityVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sync", data: BytesLike): Result;
}

export interface IAlgebraPoolPermissionedActions extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraPoolPermissionedActions;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraPoolPermissionedActionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setCommunityFee: TypedContractMethod<
    [newCommunityFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCommunityVault: TypedContractMethod<
    [newCommunityVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  setPlugin: TypedContractMethod<
    [newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPluginConfig: TypedContractMethod<
    [newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTickSpacing: TypedContractMethod<
    [newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  skim: TypedContractMethod<[], [void], "nonpayable">;

  sync: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setCommunityFee"
  ): TypedContractMethod<[newCommunityFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCommunityVault"
  ): TypedContractMethod<
    [newCommunityVault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlugin"
  ): TypedContractMethod<[newPluginAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPluginConfig"
  ): TypedContractMethod<[newConfig: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTickSpacing"
  ): TypedContractMethod<[newTickSpacing: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "skim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sync"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
