/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../../../common";

export interface IAlgebraPoolEventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "Burn"
      | "BurnFee"
      | "Collect"
      | "CommunityFee"
      | "CommunityVault"
      | "ExcessTokens"
      | "Fee"
      | "Flash"
      | "Initialize"
      | "Mint"
      | "Plugin"
      | "PluginConfig"
      | "Skim"
      | "Swap"
      | "SwapFee"
      | "TickSpacing"
  ): EventFragment;
}

export namespace BurnEvent {
  export type InputTuple = [
    owner: AddressLike,
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidityAmount: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    bottomTick: bigint,
    topTick: bigint,
    liquidityAmount: bigint,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    owner: string;
    bottomTick: bigint;
    topTick: bigint;
    liquidityAmount: bigint;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnFeeEvent {
  export type InputTuple = [owner: AddressLike, pluginFee: BigNumberish];
  export type OutputTuple = [owner: string, pluginFee: bigint];
  export interface OutputObject {
    owner: string;
    pluginFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectEvent {
  export type InputTuple = [
    owner: AddressLike,
    recipient: AddressLike,
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    recipient: string,
    bottomTick: bigint,
    topTick: bigint,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    owner: string;
    recipient: string;
    bottomTick: bigint;
    topTick: bigint;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommunityFeeEvent {
  export type InputTuple = [communityFeeNew: BigNumberish];
  export type OutputTuple = [communityFeeNew: bigint];
  export interface OutputObject {
    communityFeeNew: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommunityVaultEvent {
  export type InputTuple = [newCommunityVault: AddressLike];
  export type OutputTuple = [newCommunityVault: string];
  export interface OutputObject {
    newCommunityVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExcessTokensEvent {
  export type InputTuple = [amount0: BigNumberish, amount1: BigNumberish];
  export type OutputTuple = [amount0: bigint, amount1: bigint];
  export interface OutputObject {
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    paid0: BigNumberish,
    paid1: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    amount0: bigint,
    amount1: bigint,
    paid0: bigint,
    paid1: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    amount0: bigint;
    amount1: bigint;
    paid0: bigint;
    paid1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializeEvent {
  export type InputTuple = [price: BigNumberish, tick: BigNumberish];
  export type OutputTuple = [price: bigint, tick: bigint];
  export interface OutputObject {
    price: bigint;
    tick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintEvent {
  export type InputTuple = [
    sender: AddressLike,
    owner: AddressLike,
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidityAmount: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    owner: string,
    bottomTick: bigint,
    topTick: bigint,
    liquidityAmount: bigint,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    sender: string;
    owner: string;
    bottomTick: bigint;
    topTick: bigint;
    liquidityAmount: bigint;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginEvent {
  export type InputTuple = [newPluginAddress: AddressLike];
  export type OutputTuple = [newPluginAddress: string];
  export interface OutputObject {
    newPluginAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginConfigEvent {
  export type InputTuple = [newPluginConfig: BigNumberish];
  export type OutputTuple = [newPluginConfig: bigint];
  export interface OutputObject {
    newPluginConfig: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkimEvent {
  export type InputTuple = [
    to: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [to: string, amount0: bigint, amount1: bigint];
  export interface OutputObject {
    to: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    price: BigNumberish,
    liquidity: BigNumberish,
    tick: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    amount0: bigint,
    amount1: bigint,
    price: bigint,
    liquidity: bigint,
    tick: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    amount0: bigint;
    amount1: bigint;
    price: bigint;
    liquidity: bigint;
    tick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapFeeEvent {
  export type InputTuple = [
    sender: AddressLike,
    overrideFee: BigNumberish,
    pluginFee: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    overrideFee: bigint,
    pluginFee: bigint
  ];
  export interface OutputObject {
    sender: string;
    overrideFee: bigint;
    pluginFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TickSpacingEvent {
  export type InputTuple = [newTickSpacing: BigNumberish];
  export type OutputTuple = [newTickSpacing: bigint];
  export interface OutputObject {
    newTickSpacing: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAlgebraPoolEvents extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraPoolEvents;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraPoolEventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "Burn"
  ): TypedContractEvent<
    BurnEvent.InputTuple,
    BurnEvent.OutputTuple,
    BurnEvent.OutputObject
  >;
  getEvent(
    key: "BurnFee"
  ): TypedContractEvent<
    BurnFeeEvent.InputTuple,
    BurnFeeEvent.OutputTuple,
    BurnFeeEvent.OutputObject
  >;
  getEvent(
    key: "Collect"
  ): TypedContractEvent<
    CollectEvent.InputTuple,
    CollectEvent.OutputTuple,
    CollectEvent.OutputObject
  >;
  getEvent(
    key: "CommunityFee"
  ): TypedContractEvent<
    CommunityFeeEvent.InputTuple,
    CommunityFeeEvent.OutputTuple,
    CommunityFeeEvent.OutputObject
  >;
  getEvent(
    key: "CommunityVault"
  ): TypedContractEvent<
    CommunityVaultEvent.InputTuple,
    CommunityVaultEvent.OutputTuple,
    CommunityVaultEvent.OutputObject
  >;
  getEvent(
    key: "ExcessTokens"
  ): TypedContractEvent<
    ExcessTokensEvent.InputTuple,
    ExcessTokensEvent.OutputTuple,
    ExcessTokensEvent.OutputObject
  >;
  getEvent(
    key: "Fee"
  ): TypedContractEvent<
    FeeEvent.InputTuple,
    FeeEvent.OutputTuple,
    FeeEvent.OutputObject
  >;
  getEvent(
    key: "Flash"
  ): TypedContractEvent<
    FlashEvent.InputTuple,
    FlashEvent.OutputTuple,
    FlashEvent.OutputObject
  >;
  getEvent(
    key: "Initialize"
  ): TypedContractEvent<
    InitializeEvent.InputTuple,
    InitializeEvent.OutputTuple,
    InitializeEvent.OutputObject
  >;
  getEvent(
    key: "Mint"
  ): TypedContractEvent<
    MintEvent.InputTuple,
    MintEvent.OutputTuple,
    MintEvent.OutputObject
  >;
  getEvent(
    key: "Plugin"
  ): TypedContractEvent<
    PluginEvent.InputTuple,
    PluginEvent.OutputTuple,
    PluginEvent.OutputObject
  >;
  getEvent(
    key: "PluginConfig"
  ): TypedContractEvent<
    PluginConfigEvent.InputTuple,
    PluginConfigEvent.OutputTuple,
    PluginConfigEvent.OutputObject
  >;
  getEvent(
    key: "Skim"
  ): TypedContractEvent<
    SkimEvent.InputTuple,
    SkimEvent.OutputTuple,
    SkimEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "SwapFee"
  ): TypedContractEvent<
    SwapFeeEvent.InputTuple,
    SwapFeeEvent.OutputTuple,
    SwapFeeEvent.OutputObject
  >;
  getEvent(
    key: "TickSpacing"
  ): TypedContractEvent<
    TickSpacingEvent.InputTuple,
    TickSpacingEvent.OutputTuple,
    TickSpacingEvent.OutputObject
  >;

  filters: {
    "Burn(address,int24,int24,uint128,uint256,uint256)": TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;
    Burn: TypedContractEvent<
      BurnEvent.InputTuple,
      BurnEvent.OutputTuple,
      BurnEvent.OutputObject
    >;

    "BurnFee(address,uint24)": TypedContractEvent<
      BurnFeeEvent.InputTuple,
      BurnFeeEvent.OutputTuple,
      BurnFeeEvent.OutputObject
    >;
    BurnFee: TypedContractEvent<
      BurnFeeEvent.InputTuple,
      BurnFeeEvent.OutputTuple,
      BurnFeeEvent.OutputObject
    >;

    "Collect(address,address,int24,int24,uint128,uint128)": TypedContractEvent<
      CollectEvent.InputTuple,
      CollectEvent.OutputTuple,
      CollectEvent.OutputObject
    >;
    Collect: TypedContractEvent<
      CollectEvent.InputTuple,
      CollectEvent.OutputTuple,
      CollectEvent.OutputObject
    >;

    "CommunityFee(uint16)": TypedContractEvent<
      CommunityFeeEvent.InputTuple,
      CommunityFeeEvent.OutputTuple,
      CommunityFeeEvent.OutputObject
    >;
    CommunityFee: TypedContractEvent<
      CommunityFeeEvent.InputTuple,
      CommunityFeeEvent.OutputTuple,
      CommunityFeeEvent.OutputObject
    >;

    "CommunityVault(address)": TypedContractEvent<
      CommunityVaultEvent.InputTuple,
      CommunityVaultEvent.OutputTuple,
      CommunityVaultEvent.OutputObject
    >;
    CommunityVault: TypedContractEvent<
      CommunityVaultEvent.InputTuple,
      CommunityVaultEvent.OutputTuple,
      CommunityVaultEvent.OutputObject
    >;

    "ExcessTokens(uint256,uint256)": TypedContractEvent<
      ExcessTokensEvent.InputTuple,
      ExcessTokensEvent.OutputTuple,
      ExcessTokensEvent.OutputObject
    >;
    ExcessTokens: TypedContractEvent<
      ExcessTokensEvent.InputTuple,
      ExcessTokensEvent.OutputTuple,
      ExcessTokensEvent.OutputObject
    >;

    "Fee(uint16)": TypedContractEvent<
      FeeEvent.InputTuple,
      FeeEvent.OutputTuple,
      FeeEvent.OutputObject
    >;
    Fee: TypedContractEvent<
      FeeEvent.InputTuple,
      FeeEvent.OutputTuple,
      FeeEvent.OutputObject
    >;

    "Flash(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FlashEvent.InputTuple,
      FlashEvent.OutputTuple,
      FlashEvent.OutputObject
    >;
    Flash: TypedContractEvent<
      FlashEvent.InputTuple,
      FlashEvent.OutputTuple,
      FlashEvent.OutputObject
    >;

    "Initialize(uint160,int24)": TypedContractEvent<
      InitializeEvent.InputTuple,
      InitializeEvent.OutputTuple,
      InitializeEvent.OutputObject
    >;
    Initialize: TypedContractEvent<
      InitializeEvent.InputTuple,
      InitializeEvent.OutputTuple,
      InitializeEvent.OutputObject
    >;

    "Mint(address,address,int24,int24,uint128,uint256,uint256)": TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;
    Mint: TypedContractEvent<
      MintEvent.InputTuple,
      MintEvent.OutputTuple,
      MintEvent.OutputObject
    >;

    "Plugin(address)": TypedContractEvent<
      PluginEvent.InputTuple,
      PluginEvent.OutputTuple,
      PluginEvent.OutputObject
    >;
    Plugin: TypedContractEvent<
      PluginEvent.InputTuple,
      PluginEvent.OutputTuple,
      PluginEvent.OutputObject
    >;

    "PluginConfig(uint8)": TypedContractEvent<
      PluginConfigEvent.InputTuple,
      PluginConfigEvent.OutputTuple,
      PluginConfigEvent.OutputObject
    >;
    PluginConfig: TypedContractEvent<
      PluginConfigEvent.InputTuple,
      PluginConfigEvent.OutputTuple,
      PluginConfigEvent.OutputObject
    >;

    "Skim(address,uint256,uint256)": TypedContractEvent<
      SkimEvent.InputTuple,
      SkimEvent.OutputTuple,
      SkimEvent.OutputObject
    >;
    Skim: TypedContractEvent<
      SkimEvent.InputTuple,
      SkimEvent.OutputTuple,
      SkimEvent.OutputObject
    >;

    "Swap(address,address,int256,int256,uint160,uint128,int24)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "SwapFee(address,uint24,uint24)": TypedContractEvent<
      SwapFeeEvent.InputTuple,
      SwapFeeEvent.OutputTuple,
      SwapFeeEvent.OutputObject
    >;
    SwapFee: TypedContractEvent<
      SwapFeeEvent.InputTuple,
      SwapFeeEvent.OutputTuple,
      SwapFeeEvent.OutputObject
    >;

    "TickSpacing(int24)": TypedContractEvent<
      TickSpacingEvent.InputTuple,
      TickSpacingEvent.OutputTuple,
      TickSpacingEvent.OutputObject
    >;
    TickSpacing: TypedContractEvent<
      TickSpacingEvent.InputTuple,
      TickSpacingEvent.OutputTuple,
      TickSpacingEvent.OutputObject
    >;
  };
}
