/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace AssetHubVault {
  export type ChainConfigStruct = {
    supported: boolean;
    xcmDestination: BytesLike;
    chainName: string;
    timestamp: BigNumberish;
  };

  export type ChainConfigStructOutput = [
    supported: boolean,
    xcmDestination: string,
    chainName: string,
    timestamp: bigint
  ] & {
    supported: boolean;
    xcmDestination: string;
    chainName: string;
    timestamp: bigint;
  };

  export type PositionStruct = {
    user: AddressLike;
    poolId: AddressLike;
    baseAsset: AddressLike;
    chainId: BigNumberish;
    lowerRangePercent: BigNumberish;
    upperRangePercent: BigNumberish;
    timestamp: BigNumberish;
    status: BigNumberish;
    amount: BigNumberish;
    remotePositionId: BytesLike;
  };

  export type PositionStructOutput = [
    user: string,
    poolId: string,
    baseAsset: string,
    chainId: bigint,
    lowerRangePercent: bigint,
    upperRangePercent: bigint,
    timestamp: bigint,
    status: bigint,
    amount: bigint,
    remotePositionId: string
  ] & {
    user: string;
    poolId: string;
    baseAsset: string;
    chainId: bigint;
    lowerRangePercent: bigint;
    upperRangePercent: bigint;
    timestamp: bigint;
    status: bigint;
    amount: bigint;
    remotePositionId: string;
  };
}

export interface AssetHubVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "XCM_PRECOMPILE"
      | "XCM_SENDER"
      | "addChain"
      | "admin"
      | "chainExecutors"
      | "confirmExecution"
      | "deposit"
      | "dispatchInvestment"
      | "emergency"
      | "emergencyLiquidatePosition"
      | "freezeTrustedSettlementCaller"
      | "freezeXcmPrecompile"
      | "freezeXcmSender"
      | "getChainConfig"
      | "getPosition"
      | "getUserBalance"
      | "getUserPositionCount"
      | "getUserPositionIds"
      | "getUserPositionStats"
      | "getUserPositionsByStatus"
      | "getUserPositionsPage"
      | "isChainSupported"
      | "isPositionActive"
      | "operator"
      | "pause"
      | "paused"
      | "positions"
      | "removeChain"
      | "setEmergency"
      | "setOperator"
      | "setTestMode"
      | "setTrustedSettlementCaller"
      | "setXcmPrecompile"
      | "setXcmSender"
      | "settleLiquidation"
      | "supportedChains"
      | "testMode"
      | "transferAdmin"
      | "trustedSettlementCaller"
      | "trustedSettlementCallerFrozen"
      | "unpause"
      | "updateChainExecutor"
      | "userBalances"
      | "userPositions"
      | "withdraw"
      | "xcmPrecompileFrozen"
      | "xcmSenderFrozen"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainAdded"
      | "ChainRemoved"
      | "Deposit"
      | "ExecutorUpdated"
      | "InvestmentInitiated"
      | "LiquidationSettled"
      | "PositionExecutionConfirmed"
      | "PositionLiquidated"
      | "TrustedSettlementCallerSet"
      | "Withdrawal"
      | "XCMMessageSent"
      | "XcmPrecompileSet"
      | "XcmSendAttempt"
      | "XcmSenderSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XCM_SENDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChain",
    values: [BigNumberish, BytesLike, string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chainExecutors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmExecution",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dispatchInvestment",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "emergency", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyLiquidatePosition",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeTrustedSettlementCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "freezeXcmPrecompile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "freezeXcmSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionIds",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionsByStatus",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionsPage",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPositionActive",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergency",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedSettlementCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setXcmPrecompile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setXcmSender",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleLiquidation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "testMode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedSettlementCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedSettlementCallerFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateChainExecutor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmPrecompileFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xcmSenderFrozen",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "XCM_SENDER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addChain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dispatchInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "emergency", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyLiquidatePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeTrustedSettlementCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeXcmPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeXcmSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionsPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPositionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedSettlementCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setXcmPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setXcmSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testMode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedSettlementCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedSettlementCallerFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateChainExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xcmPrecompileFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xcmSenderFrozen",
    data: BytesLike
  ): Result;
}

export namespace ChainAddedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    xcmDestination: BytesLike,
    executor: AddressLike
  ];
  export type OutputTuple = [
    chainId: bigint,
    xcmDestination: string,
    executor: string
  ];
  export interface OutputObject {
    chainId: bigint;
    xcmDestination: string;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainRemovedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, executor: AddressLike];
  export type OutputTuple = [chainId: bigint, executor: string];
  export interface OutputObject {
    chainId: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentInitiatedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    user: AddressLike,
    chainId: BigNumberish,
    poolId: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    user: string,
    chainId: bigint,
    poolId: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    user: string;
    chainId: bigint;
    poolId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationSettledEvent {
  export type InputTuple = [
    positionId: BytesLike,
    user: AddressLike,
    receivedAmount: BigNumberish,
    expectedAmount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    user: string,
    receivedAmount: bigint,
    expectedAmount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    user: string;
    receivedAmount: bigint;
    expectedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionExecutionConfirmedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    chainId: BigNumberish,
    remotePositionId: BytesLike,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    chainId: bigint,
    remotePositionId: string,
    liquidity: bigint
  ];
  export interface OutputObject {
    positionId: string;
    chainId: bigint;
    remotePositionId: string;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLiquidatedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    user: AddressLike,
    finalAmount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    user: string,
    finalAmount: bigint
  ];
  export interface OutputObject {
    positionId: string;
    user: string;
    finalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedSettlementCallerSetEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageSentEvent {
  export type InputTuple = [
    messageHash: BytesLike,
    destination: BytesLike,
    message: BytesLike
  ];
  export type OutputTuple = [
    messageHash: string,
    destination: string,
    message: string
  ];
  export interface OutputObject {
    messageHash: string;
    destination: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmPrecompileSetEvent {
  export type InputTuple = [precompile: AddressLike];
  export type OutputTuple = [precompile: string];
  export interface OutputObject {
    precompile: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmSendAttemptEvent {
  export type InputTuple = [
    messageHash: BytesLike,
    destination: BytesLike,
    success: boolean,
    errorData: BytesLike
  ];
  export type OutputTuple = [
    messageHash: string,
    destination: string,
    success: boolean,
    errorData: string
  ];
  export interface OutputObject {
    messageHash: string;
    destination: string;
    success: boolean;
    errorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmSenderSetEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetHubVault extends BaseContract {
  connect(runner?: ContractRunner | null): AssetHubVault;
  waitForDeployment(): Promise<this>;

  interface: AssetHubVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  XCM_SENDER: TypedContractMethod<[], [string], "view">;

  addChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      xcmDestination: BytesLike,
      chainName: string,
      executor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  chainExecutors: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  confirmExecution: TypedContractMethod<
    [
      positionId: BytesLike,
      remotePositionId: BytesLike,
      liquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  dispatchInvestment: TypedContractMethod<
    [
      user: AddressLike,
      chainId: BigNumberish,
      poolId: AddressLike,
      baseAsset: AddressLike,
      amount: BigNumberish,
      lowerRangePercent: BigNumberish,
      upperRangePercent: BigNumberish,
      destination: BytesLike,
      preBuiltXcmMessage: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  emergency: TypedContractMethod<[], [string], "view">;

  emergencyLiquidatePosition: TypedContractMethod<
    [chainId: BigNumberish, positionId: BytesLike],
    [void],
    "payable"
  >;

  freezeTrustedSettlementCaller: TypedContractMethod<[], [void], "nonpayable">;

  freezeXcmPrecompile: TypedContractMethod<[], [void], "nonpayable">;

  freezeXcmSender: TypedContractMethod<[], [void], "nonpayable">;

  getChainConfig: TypedContractMethod<
    [chainId: BigNumberish],
    [AssetHubVault.ChainConfigStructOutput],
    "view"
  >;

  getPosition: TypedContractMethod<
    [positionId: BytesLike],
    [AssetHubVault.PositionStructOutput],
    "view"
  >;

  getUserBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserPositionCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserPositionIds: TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [string[]],
    "view"
  >;

  getUserPositionStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        pending: bigint;
        active: bigint;
        liquidated: bigint;
      }
    ],
    "view"
  >;

  getUserPositionsByStatus: TypedContractMethod<
    [user: AddressLike, status: BigNumberish, maxResults: BigNumberish],
    [AssetHubVault.PositionStructOutput[]],
    "view"
  >;

  getUserPositionsPage: TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [AssetHubVault.PositionStructOutput[]],
    "view"
  >;

  isChainSupported: TypedContractMethod<
    [chainId: BigNumberish],
    [boolean],
    "view"
  >;

  isPositionActive: TypedContractMethod<
    [user: AddressLike, positionId: BytesLike],
    [boolean],
    "view"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  positions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        user: string;
        poolId: string;
        baseAsset: string;
        chainId: bigint;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        timestamp: bigint;
        status: bigint;
        amount: bigint;
        remotePositionId: string;
      }
    ],
    "view"
  >;

  removeChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEmergency: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  setTestMode: TypedContractMethod<[_testMode: boolean], [void], "nonpayable">;

  setTrustedSettlementCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  setXcmPrecompile: TypedContractMethod<
    [precompile: AddressLike],
    [void],
    "nonpayable"
  >;

  setXcmSender: TypedContractMethod<
    [sender: AddressLike],
    [void],
    "nonpayable"
  >;

  settleLiquidation: TypedContractMethod<
    [positionId: BytesLike, receivedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedChains: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, string, bigint] & {
        supported: boolean;
        xcmDestination: string;
        chainName: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  testMode: TypedContractMethod<[], [boolean], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedSettlementCaller: TypedContractMethod<[], [string], "view">;

  trustedSettlementCallerFrozen: TypedContractMethod<[], [boolean], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateChainExecutor: TypedContractMethod<
    [chainId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;

  userBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  xcmPrecompileFrozen: TypedContractMethod<[], [boolean], "view">;

  xcmSenderFrozen: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "XCM_SENDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      xcmDestination: BytesLike,
      chainName: string,
      executor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "chainExecutors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "confirmExecution"
  ): TypedContractMethod<
    [
      positionId: BytesLike,
      remotePositionId: BytesLike,
      liquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "dispatchInvestment"
  ): TypedContractMethod<
    [
      user: AddressLike,
      chainId: BigNumberish,
      poolId: AddressLike,
      baseAsset: AddressLike,
      amount: BigNumberish,
      lowerRangePercent: BigNumberish,
      upperRangePercent: BigNumberish,
      destination: BytesLike,
      preBuiltXcmMessage: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyLiquidatePosition"
  ): TypedContractMethod<
    [chainId: BigNumberish, positionId: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "freezeTrustedSettlementCaller"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeXcmPrecompile"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeXcmSender"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getChainConfig"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [AssetHubVault.ChainConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BytesLike],
    [AssetHubVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPositionCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPositionIds"
  ): TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        pending: bigint;
        active: bigint;
        liquidated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionsByStatus"
  ): TypedContractMethod<
    [user: AddressLike, status: BigNumberish, maxResults: BigNumberish],
    [AssetHubVault.PositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionsPage"
  ): TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [AssetHubVault.PositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isChainSupported"
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPositionActive"
  ): TypedContractMethod<
    [user: AddressLike, positionId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        user: string;
        poolId: string;
        baseAsset: string;
        chainId: bigint;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        timestamp: bigint;
        status: bigint;
        amount: bigint;
        remotePositionId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergency"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTestMode"
  ): TypedContractMethod<[_testMode: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedSettlementCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setXcmPrecompile"
  ): TypedContractMethod<[precompile: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setXcmSender"
  ): TypedContractMethod<[sender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleLiquidation"
  ): TypedContractMethod<
    [positionId: BytesLike, receivedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, string, bigint] & {
        supported: boolean;
        xcmDestination: string;
        chainName: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "testMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedSettlementCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trustedSettlementCallerFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateChainExecutor"
  ): TypedContractMethod<
    [chainId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xcmPrecompileFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "xcmSenderFrozen"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "ChainAdded"
  ): TypedContractEvent<
    ChainAddedEvent.InputTuple,
    ChainAddedEvent.OutputTuple,
    ChainAddedEvent.OutputObject
  >;
  getEvent(
    key: "ChainRemoved"
  ): TypedContractEvent<
    ChainRemovedEvent.InputTuple,
    ChainRemovedEvent.OutputTuple,
    ChainRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorUpdated"
  ): TypedContractEvent<
    ExecutorUpdatedEvent.InputTuple,
    ExecutorUpdatedEvent.OutputTuple,
    ExecutorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentInitiated"
  ): TypedContractEvent<
    InvestmentInitiatedEvent.InputTuple,
    InvestmentInitiatedEvent.OutputTuple,
    InvestmentInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationSettled"
  ): TypedContractEvent<
    LiquidationSettledEvent.InputTuple,
    LiquidationSettledEvent.OutputTuple,
    LiquidationSettledEvent.OutputObject
  >;
  getEvent(
    key: "PositionExecutionConfirmed"
  ): TypedContractEvent<
    PositionExecutionConfirmedEvent.InputTuple,
    PositionExecutionConfirmedEvent.OutputTuple,
    PositionExecutionConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLiquidated"
  ): TypedContractEvent<
    PositionLiquidatedEvent.InputTuple,
    PositionLiquidatedEvent.OutputTuple,
    PositionLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedSettlementCallerSet"
  ): TypedContractEvent<
    TrustedSettlementCallerSetEvent.InputTuple,
    TrustedSettlementCallerSetEvent.OutputTuple,
    TrustedSettlementCallerSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageSent"
  ): TypedContractEvent<
    XCMMessageSentEvent.InputTuple,
    XCMMessageSentEvent.OutputTuple,
    XCMMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "XcmPrecompileSet"
  ): TypedContractEvent<
    XcmPrecompileSetEvent.InputTuple,
    XcmPrecompileSetEvent.OutputTuple,
    XcmPrecompileSetEvent.OutputObject
  >;
  getEvent(
    key: "XcmSendAttempt"
  ): TypedContractEvent<
    XcmSendAttemptEvent.InputTuple,
    XcmSendAttemptEvent.OutputTuple,
    XcmSendAttemptEvent.OutputObject
  >;
  getEvent(
    key: "XcmSenderSet"
  ): TypedContractEvent<
    XcmSenderSetEvent.InputTuple,
    XcmSenderSetEvent.OutputTuple,
    XcmSenderSetEvent.OutputObject
  >;

  filters: {
    "ChainAdded(uint32,bytes,address)": TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;
    ChainAdded: TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;

    "ChainRemoved(uint32)": TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;
    ChainRemoved: TypedContractEvent<
      ChainRemovedEvent.InputTuple,
      ChainRemovedEvent.OutputTuple,
      ChainRemovedEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ExecutorUpdated(uint32,address)": TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;
    ExecutorUpdated: TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;

    "InvestmentInitiated(bytes32,address,uint32,address,uint256)": TypedContractEvent<
      InvestmentInitiatedEvent.InputTuple,
      InvestmentInitiatedEvent.OutputTuple,
      InvestmentInitiatedEvent.OutputObject
    >;
    InvestmentInitiated: TypedContractEvent<
      InvestmentInitiatedEvent.InputTuple,
      InvestmentInitiatedEvent.OutputTuple,
      InvestmentInitiatedEvent.OutputObject
    >;

    "LiquidationSettled(bytes32,address,uint256,uint256)": TypedContractEvent<
      LiquidationSettledEvent.InputTuple,
      LiquidationSettledEvent.OutputTuple,
      LiquidationSettledEvent.OutputObject
    >;
    LiquidationSettled: TypedContractEvent<
      LiquidationSettledEvent.InputTuple,
      LiquidationSettledEvent.OutputTuple,
      LiquidationSettledEvent.OutputObject
    >;

    "PositionExecutionConfirmed(bytes32,uint32,bytes32,uint128)": TypedContractEvent<
      PositionExecutionConfirmedEvent.InputTuple,
      PositionExecutionConfirmedEvent.OutputTuple,
      PositionExecutionConfirmedEvent.OutputObject
    >;
    PositionExecutionConfirmed: TypedContractEvent<
      PositionExecutionConfirmedEvent.InputTuple,
      PositionExecutionConfirmedEvent.OutputTuple,
      PositionExecutionConfirmedEvent.OutputObject
    >;

    "PositionLiquidated(bytes32,address,uint256)": TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;
    PositionLiquidated: TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;

    "TrustedSettlementCallerSet(address)": TypedContractEvent<
      TrustedSettlementCallerSetEvent.InputTuple,
      TrustedSettlementCallerSetEvent.OutputTuple,
      TrustedSettlementCallerSetEvent.OutputObject
    >;
    TrustedSettlementCallerSet: TypedContractEvent<
      TrustedSettlementCallerSetEvent.InputTuple,
      TrustedSettlementCallerSetEvent.OutputTuple,
      TrustedSettlementCallerSetEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "XCMMessageSent(bytes32,bytes,bytes)": TypedContractEvent<
      XCMMessageSentEvent.InputTuple,
      XCMMessageSentEvent.OutputTuple,
      XCMMessageSentEvent.OutputObject
    >;
    XCMMessageSent: TypedContractEvent<
      XCMMessageSentEvent.InputTuple,
      XCMMessageSentEvent.OutputTuple,
      XCMMessageSentEvent.OutputObject
    >;

    "XcmPrecompileSet(address)": TypedContractEvent<
      XcmPrecompileSetEvent.InputTuple,
      XcmPrecompileSetEvent.OutputTuple,
      XcmPrecompileSetEvent.OutputObject
    >;
    XcmPrecompileSet: TypedContractEvent<
      XcmPrecompileSetEvent.InputTuple,
      XcmPrecompileSetEvent.OutputTuple,
      XcmPrecompileSetEvent.OutputObject
    >;

    "XcmSendAttempt(bytes32,bytes,bool,bytes)": TypedContractEvent<
      XcmSendAttemptEvent.InputTuple,
      XcmSendAttemptEvent.OutputTuple,
      XcmSendAttemptEvent.OutputObject
    >;
    XcmSendAttempt: TypedContractEvent<
      XcmSendAttemptEvent.InputTuple,
      XcmSendAttemptEvent.OutputTuple,
      XcmSendAttemptEvent.OutputObject
    >;

    "XcmSenderSet(address)": TypedContractEvent<
      XcmSenderSetEvent.InputTuple,
      XcmSenderSetEvent.OutputTuple,
      XcmSenderSetEvent.OutputObject
    >;
    XcmSenderSet: TypedContractEvent<
      XcmSenderSetEvent.InputTuple,
      XcmSenderSetEvent.OutputTuple,
      XcmSenderSetEvent.OutputObject
    >;
  };
}
