/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as integralCore from "./integral-core";
export type { integralCore };
import type * as integralPeriphery from "./integral-periphery";
export type { integralPeriphery };
