// Contract ABIs extracted from compiled artifacts
// Source: SmartContracts/artifacts-evm/contracts/V1(Current)/

// ── XCMProxy (Moonbeam) ─────────────────────────────────────────────
// Key user-facing functions for the XCM Proxy on Moonbeam
export const xcmProxyAbi = [
  {
    inputs: [
      { internalType: "bytes32", name: "assetHubPositionId", type: "bytes32" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bytes", name: "investmentParams", type: "bytes" },
    ],
    name: "receiveAssets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "beneficiary", type: "address" },
    ],
    name: "returnAssets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "getBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "start", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
    ],
    name: "getUserPositions",
    outputs: [{ internalType: "uint256[]", name: "ids", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserPositionCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "pendingPositions",
    outputs: [
      { internalType: "bytes32", name: "assetHubPositionId", type: "bytes32" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "poolId", type: "address" },
      { internalType: "address", name: "baseAsset", type: "address" },
      { internalType: "int24", name: "lowerRangePercent", type: "int24" },
      { internalType: "int24", name: "upperRangePercent", type: "int24" },
      { internalType: "uint16", name: "slippageBps", type: "uint16" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "bool", name: "exists", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "positions",
    outputs: [
      { internalType: "bytes32", name: "assetHubPositionId", type: "bytes32" },
      { internalType: "address", name: "pool", type: "address" },
      { internalType: "address", name: "token0", type: "address" },
      { internalType: "address", name: "token1", type: "address" },
      { internalType: "int24", name: "bottomTick", type: "int24" },
      { internalType: "int24", name: "topTick", type: "int24" },
      { internalType: "uint128", name: "liquidity", type: "uint128" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "int24", name: "lowerRangePercent", type: "int24" },
      { internalType: "int24", name: "upperRangePercent", type: "int24" },
      { internalType: "uint256", name: "entryPrice", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "uint256", name: "liquidatedAmount0", type: "uint256" },
      { internalType: "uint256", name: "liquidatedAmount1", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "assetHubPositionId", type: "bytes32" }],
    name: "cancelPendingPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    name: "collectFees",
    outputs: [
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "assetHubPositionId", type: "bytes32" }],
    name: "executePendingInvestment",
    outputs: [{ internalType: "uint256", name: "localPositionId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "supportedTokens",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

// ── AssetHubVault (Asset Hub / Substrate) ────────────────────────────
// Key user-facing functions for the vault on Asset Hub
export const assetHubVaultAbi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "positionId", type: "bytes32" }],
    name: "getPosition",
    outputs: [
      {
        components: [
          { internalType: "address", name: "user", type: "address" },
          { internalType: "address", name: "poolId", type: "address" },
          { internalType: "address", name: "baseAsset", type: "address" },
          { internalType: "uint32", name: "chainId", type: "uint32" },
          { internalType: "int24", name: "lowerRangePercent", type: "int24" },
          { internalType: "int24", name: "upperRangePercent", type: "int24" },
          { internalType: "uint64", name: "timestamp", type: "uint64" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bytes32", name: "remotePositionId", type: "bytes32" },
          { internalType: "uint256", name: "settledAmount", type: "uint256" },
        ],
        internalType: "struct AssetHubVault.Position",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserPositionCount",
    outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "start", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
    ],
    name: "getUserPositionIds",
    outputs: [{ internalType: "bytes32[]", name: "positionIds", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserPositionStats",
    outputs: [
      { internalType: "uint256", name: "total", type: "uint256" },
      { internalType: "uint256", name: "pending", type: "uint256" },
      { internalType: "uint256", name: "active", type: "uint256" },
      { internalType: "uint256", name: "liquidated", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "uint256", name: "maxResults", type: "uint256" },
    ],
    name: "getUserPositionsByStatus",
    outputs: [
      {
        components: [
          { internalType: "address", name: "user", type: "address" },
          { internalType: "address", name: "poolId", type: "address" },
          { internalType: "address", name: "baseAsset", type: "address" },
          { internalType: "uint32", name: "chainId", type: "uint32" },
          { internalType: "int24", name: "lowerRangePercent", type: "int24" },
          { internalType: "int24", name: "upperRangePercent", type: "int24" },
          { internalType: "uint64", name: "timestamp", type: "uint64" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bytes32", name: "remotePositionId", type: "bytes32" },
          { internalType: "uint256", name: "settledAmount", type: "uint256" },
        ],
        internalType: "struct AssetHubVault.Position[]",
        name: "list",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "start", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
    ],
    name: "getUserPositionsPage",
    outputs: [
      {
        components: [
          { internalType: "address", name: "user", type: "address" },
          { internalType: "address", name: "poolId", type: "address" },
          { internalType: "address", name: "baseAsset", type: "address" },
          { internalType: "uint32", name: "chainId", type: "uint32" },
          { internalType: "int24", name: "lowerRangePercent", type: "int24" },
          { internalType: "int24", name: "upperRangePercent", type: "int24" },
          { internalType: "uint64", name: "timestamp", type: "uint64" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bytes32", name: "remotePositionId", type: "bytes32" },
          { internalType: "uint256", name: "settledAmount", type: "uint256" },
        ],
        internalType: "struct AssetHubVault.Position[]",
        name: "list",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "bytes32", name: "positionId", type: "bytes32" },
    ],
    name: "isPositionActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint32", name: "chainId", type: "uint32" },
      { internalType: "address", name: "poolId", type: "address" },
      { internalType: "address", name: "baseAsset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "int24", name: "lowerRangePercent", type: "int24" },
      { internalType: "int24", name: "upperRangePercent", type: "int24" },
      { internalType: "bytes", name: "destination", type: "bytes" },
      { internalType: "bytes", name: "preBuiltXcmMessage", type: "bytes" },
    ],
    name: "dispatchInvestment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

// ── ERC20 (minimal interface) ────────────────────────────────────────
export const erc20Abi = [
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
