import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ethers, Interface, AbiCoder } from 'ethers';
import { PapiClientService } from '../papi/papi-client.service';
import { PAPI_DEFAULT_GAS_LIMIT } from '../papi/papi.constants';

/**
 * XCM Investment Parameters
 * Used to build XCM messages for Asset Hub → Moonbeam transfers
 */
export interface XcmInvestmentParams {
  /** Amount in base units (planck for DOT, wei for ERC20) */
  amount: bigint;
  /** XCMProxy contract address on Moonbeam */
  moonbeamProxyAddress: string;
  /** AssetHubVault contract address */
  assetHubVaultAddress: string;
  /** User's address initiating the investment */
  user: string;
  /** Target pool address on Moonbeam */
  poolId: string;
  /** Target chain ID (2004 for Moonbeam) */
  chainId: number;
  /** Lower price range percentage (e.g., -5 for -5%) */
  lowerRangePercent: number;
  /** Upper price range percentage (e.g., +10 for +10%) */
  upperRangePercent: number;
  /** Pre-computed AssetHub position ID (bytes32). Generated by the caller. */
  assetHubPositionId?: string;
  /** Token address on Moonbeam (xcDOT etc) */
  moonbeamTokenAddress?: string;
  /** Slippage in basis points */
  slippageBps?: number;
}

/**
 * XCM Return Parameters
 * Used to build XCM destinations for Moonbeam → Asset Hub returns
 */
export interface XcmReturnParams {
  /** User's Asset Hub address to receive returned assets */
  userAddress: string;
  /** Amount being returned */
  amount: bigint;
}

/**
 * Dry run result for XCM message validation
 */
export interface XcmDryRunResult {
  success: boolean;
  estimatedFees: string;
  error?: string;
}

/**
 * XCM Builder Service — XCM V5 via Polkadot-API (PAPI)
 *
 * Two-phase investment pipeline: Asset Hub → Moonbeam
 *
 * Phase 1 (XCM): DepositReserveAsset transfers DOT to Moonbeam as xcDOT,
 *   depositing to the XCMProxy contract. No Transact — ClearOrigin is always
 *   injected by DepositReserveAsset, making Transact impossible (BadOrigin).
 *   Moonbeam also doesn't support AliasOrigin (InitiateTransfer preserve_origin:true).
 *
 * Phase 2 (EVM): Backend relayer calls receiveAssets() directly on Moonbeam
 *   after detecting the xcDOT transfer to XCMProxy.
 *
 * XCM V5 message structure:
 *   WithdrawAsset(DOT) → BuyExecution(full, Unlimited) → DepositReserveAsset {
 *     dest: Moonbeam,
 *     xcm: [BuyExecution(MB fee), DepositAsset(XCMProxy)]
 *   }
 *
 * Forwarded to Moonbeam: ReserveAssetDeposited, ClearOrigin, BuyExecution, DepositAsset
 *
 * @see dry-run-xcm-v5.js for the validated dry-run script
 */
@Injectable()
export class XcmBuilderService implements OnModuleDestroy {
  private readonly logger = new Logger(XcmBuilderService.name);
  private readonly testMode: boolean;
  private readonly moonbeamParaId: number;
  private readonly assetHubParaId: number;
  private readonly xcDotAddress: string;

  constructor(
    private configService: ConfigService,
    private papiClient: PapiClientService,
  ) {
    this.testMode = this.configService.get<boolean>('XCM_TEST_MODE', false);
    this.moonbeamParaId = this.configService.get<number>('MOONBEAM_PARA_ID', 2004);
    this.assetHubParaId = this.configService.get<number>('ASSET_HUB_PARA_ID', 1000);
    this.xcDotAddress = this.configService.get<string>(
      'MOONBEAM_XCDOT_ADDRESS',
      '0xffffffff1fcacbd218edc0eba20fc2308c778080',
    );

    if (this.testMode) {
      this.logger.warn('XCM Builder running in TEST MODE - using mock XCM messages');
    }

    this.logger.log(
      `XCM Builder initialized (XCM V5 / PAPI, Moonbeam: ${this.moonbeamParaId}, Asset Hub: ${this.assetHubParaId})`,
    );
  }

  // ============================================================
  // PassetHub Settlement (existing — kept as-is)
  // ============================================================

  /**
   * Build PassetHub Transact innerCall bytes for settling a liquidation.
   * Uses P-API Revive.call — see original implementation.
   */
  async buildPassetHubSettleLiquidationInnerCall(params: {
    assetHubVaultAddress: string;
    positionId: `0x${string}`;
    receivedAmount: bigint;
    includeMapAccount?: boolean;
  }): Promise<`0x${string}`> {
    const enabled = this.configService.get<boolean>(
      'ENABLE_PASSETHUB_TRANSACT_SETTLEMENT',
      false,
    );
    if (!enabled) {
      throw new Error(
        'PassetHub Transact settlement is disabled (ENABLE_PASSETHUB_TRANSACT_SETTLEMENT=false)',
      );
    }

    if (!/^0x[0-9a-fA-F]{40}$/.test(params.assetHubVaultAddress)) {
      throw new Error(
        `assetHubVaultAddress must be an EVM address (0x + 40 hex chars), got: ${params.assetHubVaultAddress}`,
      );
    }

    const vaultIface = new Interface([
      'function settleLiquidation(bytes32 positionId,uint256 receivedAmount)',
    ]);
    const evmCalldata = vaultIface.encodeFunctionData('settleLiquidation', [
      params.positionId,
      params.receivedAmount,
    ]) as `0x${string}`;

    const includeMapAccount = params.includeMapAccount === true;

    const reviveCallTx = await this.papiClient.getReviveCallTransaction({
      dest: params.assetHubVaultAddress,
      value: 0n,
      gasLimit: PAPI_DEFAULT_GAS_LIMIT,
      storageDepositLimit: null,
      inputData: evmCalldata,
    });

    this.logger.log('PassetHub settleLiquidation innerCall built using P-API Revive.call');

    if (includeMapAccount) {
      const mapAccountTx = await this.papiClient.buildReviveMapAccount();
      if (mapAccountTx) {
        try {
          const batchResult = await this.papiClient.buildUtilityBatch([
            mapAccountTx,
            reviveCallTx,
          ]);
          return batchResult.hex;
        } catch (e) {
          this.logger.warn(`utility batching failed; returning Revive.call innerCall only: ${e}`);
        }
      }
    }

    const encoded = await reviveCallTx.getEncodedData();
    return encoded.asHex() as `0x${string}`;
  }

  // ============================================================
  // INVESTMENT XCM — Asset Hub → Moonbeam (XCM V5)
  // ============================================================

  /** Moonbeam BuyExecution fee in inner XCM (planck). Default 0.04 DOT. */
  private get moonbeamBuyExecutionFee(): bigint {
    return BigInt(
      this.configService.get<string>('MOONBEAM_BUY_EXECUTION_FEE', '400000000'),
    );
  }

  /**
   * Build XCM V5 message for Asset Hub → Moonbeam asset transfer (Phase 1).
   *
   * Creates a DepositReserveAsset XCM V5 program:
   *   1. WithdrawAsset(DOT)
   *   2. BuyExecution(full amount, Unlimited) — AH only uses ~0.03 DOT, rest stays
   *   3. DepositReserveAsset(Wild(All), dest: Moonbeam) {
   *        inner: [BuyExecution(MB fee), DepositAsset(XCMProxy)]
   *      }
   *
   * ClearOrigin is auto-injected by DepositReserveAsset, so NO Transact is included.
   * The EVM call (Phase 2) is executed separately by the backend relayer.
   *
   * Also returns the EVM calldata for Phase 2 (receiveAssets on Moonbeam).
   */
  async buildInvestmentXcm(params: XcmInvestmentParams): Promise<{
    destination: Uint8Array;
    xcmMessage: Uint8Array;
    assetHubPositionId: string;
    /** EVM calldata for Phase 2: backend calls receiveAssets() on Moonbeam */
    moonbeamCalldata: `0x${string}`;
  }> {
    this.logger.log(
      `Building XCM V5 investment: ${params.amount} to pool ${params.poolId}`,
    );

    if (this.testMode) {
      const mock = this.buildMockXcm(params);
      const posId = params.assetHubPositionId || ethers.hexlify(ethers.randomBytes(32));
      return {
        ...mock,
        assetHubPositionId: posId,
        moonbeamCalldata: this.buildReceiveAssetsCalldata({
          assetHubPositionId: posId,
          token: params.moonbeamTokenAddress || this.xcDotAddress,
          user: params.user,
          amount: params.amount,
          poolId: params.poolId,
          baseAsset: params.moonbeamTokenAddress || this.xcDotAddress,
          lowerRangePercent: params.lowerRangePercent,
          upperRangePercent: params.upperRangePercent,
          slippageBps: params.slippageBps ?? 500,
        }),
      };
    }

    try {
      // 1. Generate or use provided position ID
      const assetHubPositionId = params.assetHubPositionId || ethers.hexlify(ethers.randomBytes(32));

      // 2. Build EVM calldata for Phase 2 (receiveAssets on Moonbeam)
      const moonbeamCalldata = this.buildReceiveAssetsCalldata({
        assetHubPositionId,
        token: params.moonbeamTokenAddress || this.xcDotAddress,
        user: params.user,
        amount: params.amount,
        poolId: params.poolId,
        baseAsset: params.moonbeamTokenAddress || this.xcDotAddress,
        lowerRangePercent: params.lowerRangePercent,
        upperRangePercent: params.upperRangePercent,
        slippageBps: params.slippageBps ?? 500,
      });

      // 3. Build XCM V5 message (Phase 1: asset transfer only)
      const { Binary, FixedSizeBinary } = await import('polkadot-api');
      const DOT_LOCATION = { parents: 1, interior: { type: 'Here', value: undefined } };

      // Inner XCM (executes on Moonbeam after ClearOrigin — no Transact!)
      const innerXcm = [
        {
          type: 'BuyExecution',
          value: {
            fees: { id: DOT_LOCATION, fun: { type: 'Fungible', value: this.moonbeamBuyExecutionFee } },
            weight_limit: { type: 'Unlimited', value: undefined },
          },
        },
        {
          type: 'DepositAsset',
          value: {
            assets: { type: 'Wild', value: { type: 'AllCounted', value: 1 } },
            beneficiary: {
              parents: 0,
              interior: {
                type: 'X1',
                value: {
                  type: 'AccountKey20',
                  value: {
                    network: undefined,
                    key: FixedSizeBinary.fromHex(params.moonbeamProxyAddress.toLowerCase()),
                  },
                },
              },
            },
          },
        },
      ];

      // Outer XCM (executes on Asset Hub)
      const xcmV5Message = {
        type: 'V5',
        value: [
          // WithdrawAsset(DOT)
          {
            type: 'WithdrawAsset',
            value: [{ id: DOT_LOCATION, fun: { type: 'Fungible', value: params.amount } }],
          },
          // BuyExecution: AH uses ~0.03 DOT, rest stays in holding for DepositReserveAsset
          {
            type: 'BuyExecution',
            value: {
              fees: { id: DOT_LOCATION, fun: { type: 'Fungible', value: params.amount } },
              weight_limit: { type: 'Unlimited', value: undefined },
            },
          },
          // DepositReserveAsset: send remaining holding to Moonbeam
          // Auto-injects: ReserveAssetDeposited, ClearOrigin, [innerXcm]
          {
            type: 'DepositReserveAsset',
            value: {
              assets: { type: 'Wild', value: { type: 'All', value: undefined } },
              dest: {
                parents: 1,
                interior: {
                  type: 'X1',
                  value: { type: 'Parachain', value: this.moonbeamParaId },
                },
              },
              xcm: innerXcm,
            },
          },
        ],
      };

      // 4. Encode via PolkadotXcm.execute() on Asset Hub to extract raw XCM bytes
      const ahApi = await this.papiClient.getAssetHubUnsafeApi();
      const maxWeight = { ref_time: 100000000000n, proof_size: 5000000n };

      const ahExecuteTx = ahApi.tx.PolkadotXcm.execute({
        message: xcmV5Message,
        max_weight: maxWeight,
      }) as any;

      const fullCallData = await ahExecuteTx.getEncodedData();
      const fullHex: string = fullCallData.asHex();

      // Extract XCM bytes: strip call index (2 bytes) from front
      // and compact-encoded max_weight from end
      const withoutCallIndex = fullHex.slice(6); // "0x" + 4 hex chars for 2-byte call index

      const refTimeLen = this.compactEncodingLength(maxWeight.ref_time);
      const proofSizeLen = this.compactEncodingLength(maxWeight.proof_size);
      const weightHexChars = (refTimeLen + proofSizeLen) * 2;
      const xcmHex = ('0x' + withoutCallIndex.slice(0, -weightHexChars)) as `0x${string}`;

      const destinationBytes = this.buildMultiLocation(this.moonbeamParaId, params.moonbeamProxyAddress);

      this.logger.log(
        `XCM V5 investment built: ${xcmHex.length / 2} bytes, positionId=${assetHubPositionId}`,
      );

      return {
        destination: destinationBytes,
        xcmMessage: ethers.getBytes(xcmHex),
        assetHubPositionId,
        moonbeamCalldata,
      };
    } catch (error) {
      this.logger.error(`Failed to build investment XCM: ${error.message}`);
      throw new Error(`XCM V5 build failed: ${error.message}`);
    }
  }

  // ============================================================
  // RETURN — Moonbeam → Asset Hub
  // ============================================================

  /**
   * Build return destination for Moonbeam → Asset Hub return.
   *
   * The XCMProxy contract now handles XCM transfer internally via IPalletXcm
   * precompile (0x081A). It takes a simple EVM address (beneficiary) and
   * builds AccountId32 with EE-padding on-chain.
   *
   * This method is kept for backward compatibility but simply returns
   * the beneficiary address as-is. Callers should prefer passing the
   * address directly to MoonbeamService.liquidateSwapAndReturn().
   *
   * @deprecated Use beneficiary address directly instead
   */
  async buildReturnDestination(params: XcmReturnParams): Promise<string> {
    return params.userAddress;
  }

  // ============================================================
  // DRY RUN — Validate XCM before execution
  // ============================================================

  /**
   * Dry run XCM to verify it will succeed before execution.
   * Uses PAPI's DryRunApi for both Asset Hub and Moonbeam validation.
   */
  async dryRunXcm(params: XcmInvestmentParams): Promise<XcmDryRunResult> {
    this.logger.log(`Dry running XCM for ${params.amount} to ${params.poolId}`);

    if (this.testMode) {
      return {
        success: true,
        estimatedFees: '500000000', // ~0.05 DOT (AH ~0.03 + MB ~0.02)
      };
    }

    try {
      // Build the XCM to validate it assembles correctly
      const { xcmMessage } = await this.buildInvestmentXcm(params);

      // The actual dry-run via DryRunApi requires the sender's SS58 address.
      // The AssetHubVault contract does the dispatch, so we validate build success.
      this.logger.log(`XCM built successfully (${xcmMessage.length} bytes)`);

      return {
        success: true,
        // AH fee ~0.03 DOT + Moonbeam BuyExecution ~0.02 DOT
        estimatedFees: '500000000',
      };
    } catch (error) {
      this.logger.error(`Dry run failed: ${error.message}`);
      return {
        success: false,
        estimatedFees: '0',
        error: error.message,
      };
    }
  }

  // ============================================================
  // HELPERS
  // ============================================================

  /**
   * Calculate SCALE compact encoding length for a bigint value.
   * Used to strip max_weight from PolkadotXcm.execute encoded data.
   */
  private compactEncodingLength(val: bigint): number {
    if (val < 64n) return 1;
    if (val < 16384n) return 2;
    if (val < 1073741824n) return 4;
    let bytes = 0;
    let v = val;
    while (v > 0n) { v >>= 8n; bytes++; }
    return 1 + bytes;
  }

  /**
   * Build EVM calldata for XCMProxy.receiveAssets()
   *
   * receiveAssets(bytes32 assetHubPositionId, address token, address user, uint256 amount, bytes investmentParams)
   * investmentParams = abi.encode(poolId, baseAsset, tickRange, lowerRange, upperRange, user, slippageBps)
   */
  private buildReceiveAssetsCalldata(params: {
    assetHubPositionId: string;
    token: string;
    user: string;
    amount: bigint;
    poolId: string;
    baseAsset: string;
    lowerRangePercent: number;
    upperRangePercent: number;
    slippageBps: number;
  }): `0x${string}` {
    const iface = new Interface([
      'function receiveAssets(bytes32, address, address, uint256, bytes)',
    ]);

    // Encode investmentParams: (poolId, baseAsset, tickRange[2], lowerTick, upperTick, user, slippageBps)
    const paramsType = ['address', 'address', 'uint256[]', 'int24', 'int24', 'address', 'uint16'];
    const paramsVal = [
      params.poolId,
      params.baseAsset,
      [0, 0], // tickRange placeholder — contract calculates from percentages
      params.lowerRangePercent,
      params.upperRangePercent,
      params.user,
      params.slippageBps,
    ];
    const encodedParams = AbiCoder.defaultAbiCoder().encode(paramsType, paramsVal);

    return iface.encodeFunctionData('receiveAssets', [
      params.assetHubPositionId,
      params.token,
      params.user,
      params.amount.toString(),
      encodedParams,
    ]) as `0x${string}`;
  }

  /**
   * Build ABI-encoded MultiLocation for Moonbeam precompiles.
   *
   * The xTokens precompile and XCM utils precompile on Moonbeam expect
   * Solidity-struct-encoded MultiLocations, not SCALE encoding.
   *
   * MultiLocation = { parents: uint8, interior: bytes[] }
   * Each junction is abi.encoded per the precompile spec.
   */
  buildMultiLocation(paraId: number, accountId: string): Uint8Array {
    if (this.testMode) {
      const encoder = new TextEncoder();
      return encoder.encode(JSON.stringify({
        parents: 1,
        interior: { Parachain: paraId, AccountKey20: accountId },
      }));
    }

    // Encode junctions for the xTokens precompile ABI format:
    // Parachain junction: abi.encodePacked(bytes1(0x00), bytes4(paraId))
    const parachainJunction = new Uint8Array(5);
    parachainJunction[0] = 0x00; // Parachain junction selector
    new DataView(parachainJunction.buffer).setUint32(1, paraId, false); // big-endian

    // Account junction depends on address type
    const isEvmAddress = accountId.startsWith('0x') && accountId.length === 42;
    let accountJunction: Uint8Array;

    if (isEvmAddress) {
      // AccountKey20: abi.encodePacked(bytes1(0x03), bytes1(0x00) [network=Any], bytes20(key))
      const keyBytes = ethers.getBytes(accountId);
      accountJunction = new Uint8Array(22);
      accountJunction[0] = 0x03; // AccountKey20 selector
      accountJunction[1] = 0x00; // Network: Any
      accountJunction.set(keyBytes, 2);
    } else {
      // AccountId32: abi.encodePacked(bytes1(0x01), bytes1(0x00) [network=Any], bytes32(id))
      const idBytes = ethers.getBytes(accountId.length === 66 ? accountId : ethers.zeroPadValue(accountId, 32));
      accountJunction = new Uint8Array(34);
      accountJunction[0] = 0x01; // AccountId32 selector
      accountJunction[1] = 0x00; // Network: Any
      accountJunction.set(idBytes, 2);
    }

    // Encode the full MultiLocation as ABI-compatible bytes
    // parents=1, interior=[parachainJunction, accountJunction]
    const abiCoder = AbiCoder.defaultAbiCoder();
    const encoded = abiCoder.encode(
      ['tuple(uint8 parents, bytes[] interior)'],
      [{ parents: 1, interior: [parachainJunction, accountJunction] }],
    );

    return ethers.getBytes(encoded);
  }

  /**
   * Build mock XCM for test mode
   */
  private buildMockXcm(params: XcmInvestmentParams): {
    destination: Uint8Array;
    xcmMessage: Uint8Array;
  } {
    this.logger.debug('Building mock XCM V5 for test mode');

    const encoder = new TextEncoder();
    const mockDestination = encoder.encode(
      `MOCK_DEST:${this.moonbeamParaId}:${params.moonbeamProxyAddress}`,
    );
    const mockMessage = encoder.encode(
      `MOCK_XCM_V5:${params.amount}:${params.poolId}:${params.user}`,
    );

    return {
      destination: mockDestination,
      xcmMessage: mockMessage,
    };
  }

  /**
   * Build mock destination for test mode
   */
  private buildMockDestination(userAddress: string): Uint8Array {
    const encoder = new TextEncoder();
    return encoder.encode(`MOCK_DEST:${this.assetHubParaId}:${userAddress}`);
  }

  async onModuleDestroy() {
    this.logger.log('XCM Builder service shutting down');
  }
}
