/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface AssetHubXcmSenderInterface extends Interface {
  getFunction(
    nameOrSignature: "XCM_PRECOMPILE" | "sendXcm" | "xcm"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendXcm",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "xcm", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendXcm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xcm", data: BytesLike): Result;
}

export interface AssetHubXcmSender extends BaseContract {
  connect(runner?: ContractRunner | null): AssetHubXcmSender;
  waitForDeployment(): Promise<this>;

  interface: AssetHubXcmSenderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  sendXcm: TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  xcm: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sendXcm"
  ): TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xcm"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
