/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPalletXcm } from "./IPalletXcm";
export type { IXCMTransactor } from "./IXCMTransactor";
export type { XCMProxy } from "./XCMProxy";
