/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IXCMTransactor } from "./IXCMTransactor";
export type { IXTokens } from "./IXTokens";
export type { XCMProxy } from "./XCMProxy";
