/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IPalletXcm {
  export type LocationStruct = { parents: BigNumberish; interior: BytesLike[] };

  export type LocationStructOutput = [parents: bigint, interior: string[]] & {
    parents: bigint;
    interior: string[];
  };

  export type AssetAddressInfoStruct = {
    asset: AddressLike;
    amount: BigNumberish;
  };

  export type AssetAddressInfoStructOutput = [asset: string, amount: bigint] & {
    asset: string;
    amount: bigint;
  };
}

export interface IPalletXcmInterface extends Interface {
  getFunction(
    nameOrSignature: "transferAssetsUsingTypeAndThenAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "transferAssetsUsingTypeAndThenAddress",
    values: [
      IPalletXcm.LocationStruct,
      IPalletXcm.AssetAddressInfoStruct[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "transferAssetsUsingTypeAndThenAddress",
    data: BytesLike
  ): Result;
}

export interface IPalletXcm extends BaseContract {
  connect(runner?: ContractRunner | null): IPalletXcm;
  waitForDeployment(): Promise<this>;

  interface: IPalletXcmInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  transferAssetsUsingTypeAndThenAddress: TypedContractMethod<
    [
      dest: IPalletXcm.LocationStruct,
      assets: IPalletXcm.AssetAddressInfoStruct[],
      assetsTransferType: BigNumberish,
      remoteFeesIdIndex: BigNumberish,
      feesTransferType: BigNumberish,
      customXcmOnDest: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "transferAssetsUsingTypeAndThenAddress"
  ): TypedContractMethod<
    [
      dest: IPalletXcm.LocationStruct,
      assets: IPalletXcm.AssetAddressInfoStruct[],
      assetsTransferType: BigNumberish,
      remoteFeesIdIndex: BigNumberish,
      feesTransferType: BigNumberish,
      customXcmOnDest: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
