/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface XCMProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSupportedToken"
      | "assetHubParaId"
      | "assetHubPositionToLocalId"
      | "calculateTickRange"
      | "cancelPendingPosition"
      | "collectFees"
      | "defaultSlippageBps"
      | "emergencyAdmin"
      | "emergencyPause"
      | "executeFullLiquidation"
      | "executePendingInvestment"
      | "freezeTestMode"
      | "freezeXcmConfig"
      | "getBalance"
      | "getUserPositionCount"
      | "getUserPositions"
      | "isPositionOutOfRange"
      | "liquidateIfOutOfRange"
      | "liquidateSwapAndReturn"
      | "maxDeadlineOffset"
      | "nfpmContract"
      | "onERC721Received"
      | "operator"
      | "owner"
      | "pause"
      | "paused"
      | "pendingPositions"
      | "positionCounter"
      | "positions"
      | "quoterContract"
      | "receiveAssets"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "returnAssets"
      | "setAssetHubParaId"
      | "setDefaultSlippageBps"
      | "setEmergencyAdmin"
      | "setIntegrations"
      | "setMaxDeadlineOffset"
      | "setNFPM"
      | "setOperator"
      | "setTestMode"
      | "setTrustedXcmCaller"
      | "setXcmPrecompile"
      | "setXcmTransactorPrecompile"
      | "supportedTokens"
      | "swapAndReturn"
      | "swapExactInputSingle"
      | "swapRouterContract"
      | "testMode"
      | "testModeFrozen"
      | "transferOwnership"
      | "trustedXcmCaller"
      | "unpause"
      | "userPositions"
      | "xcmConfigFrozen"
      | "xcmPrecompile"
      | "xcmTransactorPrecompile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetHubParaIdSet"
      | "AssetsReceived"
      | "AssetsReturned"
      | "DefaultSlippageSet"
      | "EmergencyAdminUpdated"
      | "LiquidationCompleted"
      | "LiquidityAdded"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PendingPositionCancelled"
      | "PendingPositionCreated"
      | "PositionCreated"
      | "PositionExecuted"
      | "PositionLiquidated"
      | "ProceedsSwapped"
      | "TestModeFrozen"
      | "TrustedXcmCallerSet"
      | "Unpaused"
      | "XcmConfigFrozen"
      | "XcmPrecompileSet"
      | "XcmTransactorPrecompileSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assetHubParaId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetHubPositionToLocalId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTickRange",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultSlippageBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeFullLiquidation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePendingInvestment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeTestMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "freezeXcmConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPositionOutOfRange",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateIfOutOfRange",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateSwapAndReturn",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDeadlineOffset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nfpmContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingPositions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "positionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoterContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAssets",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnAssets",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetHubParaId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultSlippageBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIntegrations",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDeadlineOffset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNFPM",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedXcmCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setXcmPrecompile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setXcmTransactorPrecompile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndReturn",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputSingle",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouterContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "testMode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testModeFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedXcmCaller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmConfigFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xcmPrecompile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xcmTransactorPrecompile",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetHubParaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetHubPositionToLocalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTickRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFullLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePendingInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeTestMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeXcmConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPositionOutOfRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateIfOutOfRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateSwapAndReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDeadlineOffset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nfpmContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoterContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetHubParaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIntegrations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDeadlineOffset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNFPM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedXcmCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setXcmPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setXcmTransactorPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRouterContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testMode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testModeFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedXcmCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xcmConfigFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xcmPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xcmTransactorPrecompile",
    data: BytesLike
  ): Result;
}

export namespace AssetHubParaIdSetEvent {
  export type InputTuple = [paraId: BigNumberish];
  export type OutputTuple = [paraId: bigint];
  export interface OutputObject {
    paraId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetsReceivedEvent {
  export type InputTuple = [
    token: AddressLike,
    user: AddressLike,
    amount: BigNumberish,
    investmentParams: BytesLike
  ];
  export type OutputTuple = [
    token: string,
    user: string,
    amount: bigint,
    investmentParams: string
  ];
  export interface OutputObject {
    token: string;
    user: string;
    amount: bigint;
    investmentParams: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetsReturnedEvent {
  export type InputTuple = [
    token: AddressLike,
    user: AddressLike,
    destination: BytesLike,
    amount: BigNumberish,
    positionId: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    user: string,
    destination: string,
    amount: bigint,
    positionId: bigint
  ];
  export interface OutputObject {
    token: string;
    user: string;
    destination: string;
    amount: bigint;
    positionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultSlippageSetEvent {
  export type InputTuple = [bps: BigNumberish];
  export type OutputTuple = [bps: bigint];
  export interface OutputObject {
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyAdminUpdatedEvent {
  export type InputTuple = [emergencyAdmin: AddressLike];
  export type OutputTuple = [emergencyAdmin: string];
  export interface OutputObject {
    emergencyAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationCompletedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    assetHubPositionId: BytesLike,
    user: AddressLike,
    baseAsset: AddressLike,
    totalReturned: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    assetHubPositionId: string,
    user: string,
    baseAsset: string,
    totalReturned: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    assetHubPositionId: string;
    user: string;
    baseAsset: string;
    totalReturned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    pool: AddressLike,
    recipient: AddressLike,
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidity: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    pool: string,
    recipient: string,
    bottomTick: bigint,
    topTick: bigint,
    liquidity: bigint,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    pool: string;
    recipient: string;
    bottomTick: bigint;
    topTick: bigint;
    liquidity: bigint;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingPositionCancelledEvent {
  export type InputTuple = [
    assetHubPositionId: BytesLike,
    user: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    assetHubPositionId: string,
    user: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    assetHubPositionId: string;
    user: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingPositionCreatedEvent {
  export type InputTuple = [
    assetHubPositionId: BytesLike,
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    poolId: AddressLike
  ];
  export type OutputTuple = [
    assetHubPositionId: string,
    user: string,
    token: string,
    amount: bigint,
    poolId: string
  ];
  export interface OutputObject {
    assetHubPositionId: string;
    user: string;
    token: string;
    amount: bigint;
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionCreatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    pool: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    pool: string,
    token0: string,
    token1: string,
    bottomTick: bigint,
    topTick: bigint,
    liquidity: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    pool: string;
    token0: string;
    token1: string;
    bottomTick: bigint;
    topTick: bigint;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionExecutedEvent {
  export type InputTuple = [
    assetHubPositionId: BytesLike,
    localPositionId: BigNumberish,
    nfpmTokenId: BigNumberish,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    assetHubPositionId: string,
    localPositionId: bigint,
    nfpmTokenId: bigint,
    liquidity: bigint
  ];
  export interface OutputObject {
    assetHubPositionId: string;
    localPositionId: bigint;
    nfpmTokenId: bigint;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLiquidatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProceedsSwappedEvent {
  export type InputTuple = [
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    positionId: BigNumberish
  ];
  export type OutputTuple = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    positionId: bigint
  ];
  export interface OutputObject {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    positionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TestModeFrozenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedXcmCallerSetEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmConfigFrozenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmPrecompileSetEvent {
  export type InputTuple = [precompile: AddressLike];
  export type OutputTuple = [precompile: string];
  export interface OutputObject {
    precompile: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XcmTransactorPrecompileSetEvent {
  export type InputTuple = [precompile: AddressLike];
  export type OutputTuple = [precompile: string];
  export interface OutputObject {
    precompile: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XCMProxy extends BaseContract {
  connect(runner?: ContractRunner | null): XCMProxy;
  waitForDeployment(): Promise<this>;

  interface: XCMProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  assetHubParaId: TypedContractMethod<[], [bigint], "view">;

  assetHubPositionToLocalId: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  calculateTickRange: TypedContractMethod<
    [
      pool: AddressLike,
      lowerRangePercent: BigNumberish,
      upperRangePercent: BigNumberish
    ],
    [[bigint, bigint] & { bottomTick: bigint; topTick: bigint }],
    "view"
  >;

  cancelPendingPosition: TypedContractMethod<
    [assetHubPositionId: BytesLike],
    [void],
    "nonpayable"
  >;

  collectFees: TypedContractMethod<
    [positionId: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  defaultSlippageBps: TypedContractMethod<[], [bigint], "view">;

  emergencyAdmin: TypedContractMethod<[], [string], "view">;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  executeFullLiquidation: TypedContractMethod<
    [positionId: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  executePendingInvestment: TypedContractMethod<
    [assetHubPositionId: BytesLike],
    [bigint],
    "nonpayable"
  >;

  freezeTestMode: TypedContractMethod<[], [void], "nonpayable">;

  freezeXcmConfig: TypedContractMethod<[], [void], "nonpayable">;

  getBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getUserPositionCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserPositions: TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [bigint[]],
    "view"
  >;

  isPositionOutOfRange: TypedContractMethod<
    [positionId: BigNumberish],
    [[boolean, bigint] & { outOfRange: boolean; currentPrice: bigint }],
    "view"
  >;

  liquidateIfOutOfRange: TypedContractMethod<
    [positionId: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        liquidated: boolean;
        amount0: bigint;
        amount1: bigint;
      }
    ],
    "nonpayable"
  >;

  liquidateSwapAndReturn: TypedContractMethod<
    [
      positionId: BigNumberish,
      baseAsset: AddressLike,
      beneficiary: AddressLike,
      minAmountOut0: BigNumberish,
      minAmountOut1: BigNumberish,
      limitSqrtPrice: BigNumberish,
      assetHubPositionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  maxDeadlineOffset: TypedContractMethod<[], [bigint], "view">;

  nfpmContract: TypedContractMethod<[], [string], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingPositions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        assetHubPositionId: string;
        token: string;
        user: string;
        amount: bigint;
        poolId: string;
        baseAsset: string;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        slippageBps: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  positionCounter: TypedContractMethod<[], [bigint], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        assetHubPositionId: string;
        pool: string;
        token0: string;
        token1: string;
        bottomTick: bigint;
        topTick: bigint;
        liquidity: bigint;
        tokenId: bigint;
        owner: string;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        entryPrice: bigint;
        timestamp: bigint;
        status: bigint;
        liquidatedAmount0: bigint;
        liquidatedAmount1: bigint;
      }
    ],
    "view"
  >;

  quoterContract: TypedContractMethod<[], [string], "view">;

  receiveAssets: TypedContractMethod<
    [
      assetHubPositionId: BytesLike,
      token: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      investmentParams: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  returnAssets: TypedContractMethod<
    [
      token: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      beneficiary: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setAssetHubParaId: TypedContractMethod<
    [paraId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultSlippageBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEmergencyAdmin: TypedContractMethod<
    [_emergencyAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  setIntegrations: TypedContractMethod<
    [quoter: AddressLike, router: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxDeadlineOffset: TypedContractMethod<
    [_offset: BigNumberish],
    [void],
    "nonpayable"
  >;

  setNFPM: TypedContractMethod<[nfpm: AddressLike], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  setTestMode: TypedContractMethod<[_testMode: boolean], [void], "nonpayable">;

  setTrustedXcmCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  setXcmPrecompile: TypedContractMethod<
    [precompile: AddressLike],
    [void],
    "nonpayable"
  >;

  setXcmTransactorPrecompile: TypedContractMethod<
    [precompile: AddressLike],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  swapAndReturn: TypedContractMethod<
    [
      positionId: BigNumberish,
      baseAsset: AddressLike,
      beneficiary: AddressLike,
      minAmountOut0: BigNumberish,
      minAmountOut1: BigNumberish,
      limitSqrtPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  swapExactInputSingle: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      limitSqrtPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapRouterContract: TypedContractMethod<[], [string], "view">;

  testMode: TypedContractMethod<[], [boolean], "view">;

  testModeFrozen: TypedContractMethod<[], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedXcmCaller: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  xcmConfigFrozen: TypedContractMethod<[], [boolean], "view">;

  xcmPrecompile: TypedContractMethod<[], [string], "view">;

  xcmTransactorPrecompile: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assetHubParaId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assetHubPositionToLocalId"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateTickRange"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      lowerRangePercent: BigNumberish,
      upperRangePercent: BigNumberish
    ],
    [[bigint, bigint] & { bottomTick: bigint; topTick: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelPendingPosition"
  ): TypedContractMethod<[assetHubPositionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultSlippageBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeFullLiquidation"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePendingInvestment"
  ): TypedContractMethod<
    [assetHubPositionId: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezeTestMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeXcmConfig"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPositionCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<
    [user: AddressLike, start: BigNumberish, count: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPositionOutOfRange"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [[boolean, bigint] & { outOfRange: boolean; currentPrice: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidateIfOutOfRange"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        liquidated: boolean;
        amount0: bigint;
        amount1: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidateSwapAndReturn"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      baseAsset: AddressLike,
      beneficiary: AddressLike,
      minAmountOut0: BigNumberish,
      minAmountOut1: BigNumberish,
      limitSqrtPrice: BigNumberish,
      assetHubPositionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxDeadlineOffset"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nfpmContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingPositions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        assetHubPositionId: string;
        token: string;
        user: string;
        amount: bigint;
        poolId: string;
        baseAsset: string;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        slippageBps: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "positionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        assetHubPositionId: string;
        pool: string;
        token0: string;
        token1: string;
        bottomTick: bigint;
        topTick: bigint;
        liquidity: bigint;
        tokenId: bigint;
        owner: string;
        lowerRangePercent: bigint;
        upperRangePercent: bigint;
        entryPrice: bigint;
        timestamp: bigint;
        status: bigint;
        liquidatedAmount0: bigint;
        liquidatedAmount1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoterContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveAssets"
  ): TypedContractMethod<
    [
      assetHubPositionId: BytesLike,
      token: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      investmentParams: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnAssets"
  ): TypedContractMethod<
    [
      token: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      beneficiary: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAssetHubParaId"
  ): TypedContractMethod<[paraId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultSlippageBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencyAdmin"
  ): TypedContractMethod<[_emergencyAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIntegrations"
  ): TypedContractMethod<
    [quoter: AddressLike, router: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxDeadlineOffset"
  ): TypedContractMethod<[_offset: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNFPM"
  ): TypedContractMethod<[nfpm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTestMode"
  ): TypedContractMethod<[_testMode: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedXcmCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setXcmPrecompile"
  ): TypedContractMethod<[precompile: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setXcmTransactorPrecompile"
  ): TypedContractMethod<[precompile: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapAndReturn"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      baseAsset: AddressLike,
      beneficiary: AddressLike,
      minAmountOut0: BigNumberish,
      minAmountOut1: BigNumberish,
      limitSqrtPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactInputSingle"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      limitSqrtPrice: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapRouterContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "testMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "testModeFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedXcmCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "xcmConfigFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "xcmPrecompile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "xcmTransactorPrecompile"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssetHubParaIdSet"
  ): TypedContractEvent<
    AssetHubParaIdSetEvent.InputTuple,
    AssetHubParaIdSetEvent.OutputTuple,
    AssetHubParaIdSetEvent.OutputObject
  >;
  getEvent(
    key: "AssetsReceived"
  ): TypedContractEvent<
    AssetsReceivedEvent.InputTuple,
    AssetsReceivedEvent.OutputTuple,
    AssetsReceivedEvent.OutputObject
  >;
  getEvent(
    key: "AssetsReturned"
  ): TypedContractEvent<
    AssetsReturnedEvent.InputTuple,
    AssetsReturnedEvent.OutputTuple,
    AssetsReturnedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultSlippageSet"
  ): TypedContractEvent<
    DefaultSlippageSetEvent.InputTuple,
    DefaultSlippageSetEvent.OutputTuple,
    DefaultSlippageSetEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyAdminUpdated"
  ): TypedContractEvent<
    EmergencyAdminUpdatedEvent.InputTuple,
    EmergencyAdminUpdatedEvent.OutputTuple,
    EmergencyAdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationCompleted"
  ): TypedContractEvent<
    LiquidationCompletedEvent.InputTuple,
    LiquidationCompletedEvent.OutputTuple,
    LiquidationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PendingPositionCancelled"
  ): TypedContractEvent<
    PendingPositionCancelledEvent.InputTuple,
    PendingPositionCancelledEvent.OutputTuple,
    PendingPositionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingPositionCreated"
  ): TypedContractEvent<
    PendingPositionCreatedEvent.InputTuple,
    PendingPositionCreatedEvent.OutputTuple,
    PendingPositionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionCreated"
  ): TypedContractEvent<
    PositionCreatedEvent.InputTuple,
    PositionCreatedEvent.OutputTuple,
    PositionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionExecuted"
  ): TypedContractEvent<
    PositionExecutedEvent.InputTuple,
    PositionExecutedEvent.OutputTuple,
    PositionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLiquidated"
  ): TypedContractEvent<
    PositionLiquidatedEvent.InputTuple,
    PositionLiquidatedEvent.OutputTuple,
    PositionLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "ProceedsSwapped"
  ): TypedContractEvent<
    ProceedsSwappedEvent.InputTuple,
    ProceedsSwappedEvent.OutputTuple,
    ProceedsSwappedEvent.OutputObject
  >;
  getEvent(
    key: "TestModeFrozen"
  ): TypedContractEvent<
    TestModeFrozenEvent.InputTuple,
    TestModeFrozenEvent.OutputTuple,
    TestModeFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TrustedXcmCallerSet"
  ): TypedContractEvent<
    TrustedXcmCallerSetEvent.InputTuple,
    TrustedXcmCallerSetEvent.OutputTuple,
    TrustedXcmCallerSetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "XcmConfigFrozen"
  ): TypedContractEvent<
    XcmConfigFrozenEvent.InputTuple,
    XcmConfigFrozenEvent.OutputTuple,
    XcmConfigFrozenEvent.OutputObject
  >;
  getEvent(
    key: "XcmPrecompileSet"
  ): TypedContractEvent<
    XcmPrecompileSetEvent.InputTuple,
    XcmPrecompileSetEvent.OutputTuple,
    XcmPrecompileSetEvent.OutputObject
  >;
  getEvent(
    key: "XcmTransactorPrecompileSet"
  ): TypedContractEvent<
    XcmTransactorPrecompileSetEvent.InputTuple,
    XcmTransactorPrecompileSetEvent.OutputTuple,
    XcmTransactorPrecompileSetEvent.OutputObject
  >;

  filters: {
    "AssetHubParaIdSet(uint32)": TypedContractEvent<
      AssetHubParaIdSetEvent.InputTuple,
      AssetHubParaIdSetEvent.OutputTuple,
      AssetHubParaIdSetEvent.OutputObject
    >;
    AssetHubParaIdSet: TypedContractEvent<
      AssetHubParaIdSetEvent.InputTuple,
      AssetHubParaIdSetEvent.OutputTuple,
      AssetHubParaIdSetEvent.OutputObject
    >;

    "AssetsReceived(address,address,uint256,bytes)": TypedContractEvent<
      AssetsReceivedEvent.InputTuple,
      AssetsReceivedEvent.OutputTuple,
      AssetsReceivedEvent.OutputObject
    >;
    AssetsReceived: TypedContractEvent<
      AssetsReceivedEvent.InputTuple,
      AssetsReceivedEvent.OutputTuple,
      AssetsReceivedEvent.OutputObject
    >;

    "AssetsReturned(address,address,bytes,uint256,uint256)": TypedContractEvent<
      AssetsReturnedEvent.InputTuple,
      AssetsReturnedEvent.OutputTuple,
      AssetsReturnedEvent.OutputObject
    >;
    AssetsReturned: TypedContractEvent<
      AssetsReturnedEvent.InputTuple,
      AssetsReturnedEvent.OutputTuple,
      AssetsReturnedEvent.OutputObject
    >;

    "DefaultSlippageSet(uint16)": TypedContractEvent<
      DefaultSlippageSetEvent.InputTuple,
      DefaultSlippageSetEvent.OutputTuple,
      DefaultSlippageSetEvent.OutputObject
    >;
    DefaultSlippageSet: TypedContractEvent<
      DefaultSlippageSetEvent.InputTuple,
      DefaultSlippageSetEvent.OutputTuple,
      DefaultSlippageSetEvent.OutputObject
    >;

    "EmergencyAdminUpdated(address)": TypedContractEvent<
      EmergencyAdminUpdatedEvent.InputTuple,
      EmergencyAdminUpdatedEvent.OutputTuple,
      EmergencyAdminUpdatedEvent.OutputObject
    >;
    EmergencyAdminUpdated: TypedContractEvent<
      EmergencyAdminUpdatedEvent.InputTuple,
      EmergencyAdminUpdatedEvent.OutputTuple,
      EmergencyAdminUpdatedEvent.OutputObject
    >;

    "LiquidationCompleted(uint256,bytes32,address,address,uint256)": TypedContractEvent<
      LiquidationCompletedEvent.InputTuple,
      LiquidationCompletedEvent.OutputTuple,
      LiquidationCompletedEvent.OutputObject
    >;
    LiquidationCompleted: TypedContractEvent<
      LiquidationCompletedEvent.InputTuple,
      LiquidationCompletedEvent.OutputTuple,
      LiquidationCompletedEvent.OutputObject
    >;

    "LiquidityAdded(address,address,int24,int24,uint128,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "OperatorUpdated(address)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PendingPositionCancelled(bytes32,address,uint256)": TypedContractEvent<
      PendingPositionCancelledEvent.InputTuple,
      PendingPositionCancelledEvent.OutputTuple,
      PendingPositionCancelledEvent.OutputObject
    >;
    PendingPositionCancelled: TypedContractEvent<
      PendingPositionCancelledEvent.InputTuple,
      PendingPositionCancelledEvent.OutputTuple,
      PendingPositionCancelledEvent.OutputObject
    >;

    "PendingPositionCreated(bytes32,address,address,uint256,address)": TypedContractEvent<
      PendingPositionCreatedEvent.InputTuple,
      PendingPositionCreatedEvent.OutputTuple,
      PendingPositionCreatedEvent.OutputObject
    >;
    PendingPositionCreated: TypedContractEvent<
      PendingPositionCreatedEvent.InputTuple,
      PendingPositionCreatedEvent.OutputTuple,
      PendingPositionCreatedEvent.OutputObject
    >;

    "PositionCreated(uint256,address,address,address,address,int24,int24,uint128)": TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;
    PositionCreated: TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;

    "PositionExecuted(bytes32,uint256,uint256,uint128)": TypedContractEvent<
      PositionExecutedEvent.InputTuple,
      PositionExecutedEvent.OutputTuple,
      PositionExecutedEvent.OutputObject
    >;
    PositionExecuted: TypedContractEvent<
      PositionExecutedEvent.InputTuple,
      PositionExecutedEvent.OutputTuple,
      PositionExecutedEvent.OutputObject
    >;

    "PositionLiquidated(uint256,address,uint256,uint256)": TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;
    PositionLiquidated: TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;

    "ProceedsSwapped(address,address,uint256,uint256,uint256)": TypedContractEvent<
      ProceedsSwappedEvent.InputTuple,
      ProceedsSwappedEvent.OutputTuple,
      ProceedsSwappedEvent.OutputObject
    >;
    ProceedsSwapped: TypedContractEvent<
      ProceedsSwappedEvent.InputTuple,
      ProceedsSwappedEvent.OutputTuple,
      ProceedsSwappedEvent.OutputObject
    >;

    "TestModeFrozen()": TypedContractEvent<
      TestModeFrozenEvent.InputTuple,
      TestModeFrozenEvent.OutputTuple,
      TestModeFrozenEvent.OutputObject
    >;
    TestModeFrozen: TypedContractEvent<
      TestModeFrozenEvent.InputTuple,
      TestModeFrozenEvent.OutputTuple,
      TestModeFrozenEvent.OutputObject
    >;

    "TrustedXcmCallerSet(address)": TypedContractEvent<
      TrustedXcmCallerSetEvent.InputTuple,
      TrustedXcmCallerSetEvent.OutputTuple,
      TrustedXcmCallerSetEvent.OutputObject
    >;
    TrustedXcmCallerSet: TypedContractEvent<
      TrustedXcmCallerSetEvent.InputTuple,
      TrustedXcmCallerSetEvent.OutputTuple,
      TrustedXcmCallerSetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "XcmConfigFrozen()": TypedContractEvent<
      XcmConfigFrozenEvent.InputTuple,
      XcmConfigFrozenEvent.OutputTuple,
      XcmConfigFrozenEvent.OutputObject
    >;
    XcmConfigFrozen: TypedContractEvent<
      XcmConfigFrozenEvent.InputTuple,
      XcmConfigFrozenEvent.OutputTuple,
      XcmConfigFrozenEvent.OutputObject
    >;

    "XcmPrecompileSet(address)": TypedContractEvent<
      XcmPrecompileSetEvent.InputTuple,
      XcmPrecompileSetEvent.OutputTuple,
      XcmPrecompileSetEvent.OutputObject
    >;
    XcmPrecompileSet: TypedContractEvent<
      XcmPrecompileSetEvent.InputTuple,
      XcmPrecompileSetEvent.OutputTuple,
      XcmPrecompileSetEvent.OutputObject
    >;

    "XcmTransactorPrecompileSet(address)": TypedContractEvent<
      XcmTransactorPrecompileSetEvent.InputTuple,
      XcmTransactorPrecompileSetEvent.OutputTuple,
      XcmTransactorPrecompileSetEvent.OutputObject
    >;
    XcmTransactorPrecompileSet: TypedContractEvent<
      XcmTransactorPrecompileSetEvent.InputTuple,
      XcmTransactorPrecompileSetEvent.OutputTuple,
      XcmTransactorPrecompileSetEvent.OutputObject
    >;
  };
}
