/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v1Current from "./V1(Current)";
export type { v1Current };
import type * as test from "./test";
export type { test };
export type { SimpleTest } from "./SimpleTest";
